module.exports = {
    ERR_FIELD: 'Bạn cần điền đầy đủ thông tin',
    ERR_EXIST_EMAIL: 'Địa chỉ Email không tồn tại',
    ERR_FORMAT_EMAIL: 'Địa chỉ Email không đúng định dạng',
    ERR_REGISTER_ACCOUNT: 'Không thể đăng kí tài khoản',
    ERR_FORMAT_PASSWORD: 'Mật khẩu phải chứa ít nhất 7 kí tự',
    ERR_CONFIRM_PASSWORD: 'Mật khẩu xác thực không chính xác',
    ERR_CONFIRM_OTP: 'Mã xác thực OTP không đúng',
    ERR_PASSWORD: 'Mật khẩu không chính xác',
    ERR_SEND_OTP: 'Lỗi không thể gửi OTP',
    ERR_FORMAT_PHONE: 'Số điện thoại phải là Integer',
    ERR_CREATED: 'Tạo thất bại',
    ERR_ROLE_ADMIN: 'Bạn không phải là admin',
    ERR_9_TO_11_NUMBERPHONE: 'Số điện thoại phải từ 9 đến 11 số',
    SUCCESS_REGISTER: 'Đăng kí tài khoản thành công',
    SUCCESS_LOGIN: 'Đăng nhập thành công',
    SUCCESS_SENT_OTP: 'Mã xác thực OTP đã gửi đển địa chỉ email của bạn',
    SUCCESS_UPDATE_ACCOUNT: 'Cập nhật tài khoản thành công',
    SUCCESS_CREATED: 'Tạo thành công',
}